Added API usage key to the mock API
dvsa/recalls-mock-api pull request #2
Opened 2023-07-06 13:01 UTC by JustinJohnston-alt

## Description

Recalls Mock API updated to require both an API key and access token in the header of each request.
The README updated to include the requirement for an API key.
The Postman collection has been updated to reflect changes.

Related issue: [BL-14884](https://dvsa.atlassian.net/browse/BL-14884)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have added tests that prove my fix is effective or that my feature works

2023-07-06 13:56 UTC, StuartAdamson02 approved these changes

2023-07-14 09:09 UTC, mateuszc-kainos approved these changes

2023-07-18 10:16 UTC, aaronlong approved these changes

2023-07-18 11:22 UTC, DariuszJerzewski requested changes

2023-07-18 11:22 UTC, DariuszJerzewski commented on src/util/apiUsageKey.ts
> +  return false;
@JustinJohnston-alt  - this function could be simplified

```suggestion
  return headers['X-Api-Key'] && usageTokenRegex.test(headers['X-Api-Key']);
```

2023-07-18 12:03 UTC, DariuszJerzewski approved these changes

2023-07-18 12:03 UTC, merged